name: 'Submodule Notify Parent'

on:
  #push:
    #branches:
      #- main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    name: 'Submodule Notify Parent'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Github REST API Call
      env:
        REPO_NAME: "gh-actions-fun"
        REPO_OWNER: "MarcoSterpe"
      run: |
        curl -fL --retry 3 \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches \
        -d "{\"event_type\": \"trigger-workflow\"}"
